### ─── AUTH ────────────────────────────────────────────────────────────────────

### SIGNUP
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "firstName": "souleima",
  "lastName": "Doe",
  "email": "souleima@gmail.com",
  "password": "Password@123",
  "phone": "0612345678"
}

###

### LOGIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

###

### LOGIN ADMIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

###

### FORGOT PASSWORD
POST http://localhost:8080/auth/forgot-password
Content-Type: application/json

{
  "email": "souleima@gmail.com"
}

###

### RESET PASSWORD
POST http://localhost:8080/auth/reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvdWxlaW1hQGdtYWlsLmNvbSIsImlhdCI6MTc3MzY3ODkwMiwiZXhwIjoxNzczNjgyNTAyfQ.68Tv0cTW1VTgNQ71bLgZBURTOYmR3qQPmfUhbEuVALA",
  "password": "NewPassword@123"
}

###

### CONFIRM EMAIL
POST http://localhost:8080/auth/confirm-email
Content-Type: application/json

{
  "token": "REPLACE_WITH_VERIFICATION_TOKEN"
}

###

### RESEND CONFIRMATION (protected)
POST http://localhost:8080/auth/resend-confirmation
Content-Type: application/json
Authorization: Bearer REPLACE_WITH_JWT_TOKEN

###

### GET CURRENT USER (protected)
GET http://localhost:8080/auth/me
Authorization: Bearer REPLACE_WITH_JWT_TOKEN

###

### ─── USERS (ADMIN ONLY) ────────────────────────────────────────────────────

### GET ALL USERS
GET http://localhost:8080/users
Authorization: Bearer REPLACE_WITH_ADMIN_JWT_TOKEN

###

### GET USER BY ID
GET http://localhost:8080/users/1
Authorization: Bearer REPLACE_WITH_ADMIN_JWT_TOKEN

###

### CREATE USER
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer REPLACE_WITH_ADMIN_JWT_TOKEN

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@gmail.com",
  "password": "Password@123",
  "phone": "0612345679",
  "role": "client"
}

###

### UPDATE USER
PATCH http://localhost:8080/users/1
Content-Type: application/json
Authorization: Bearer REPLACE_WITH_ADMIN_JWT_TOKEN

{
  "firstName": "Jane",
  "lastName": "Smith",
  "phone": "0698765432"
}

###

### DELETE USER
DELETE http://localhost:8080/users/1
Authorization: Bearer REPLACE_WITH_ADMIN_JWT_TOKEN

###

### TOGGLE ACTIVE
PATCH http://localhost:8080/users/1/toggle-active
Authorization: Bearer REPLACE_WITH_ADMIN_JWT_TOKEN

### ─── VARIABLES ─────────────────────────────────────────────────────────────
@baseUrl = http://localhost:8080
@adminToken = REPLACE_WITH_ADMIN_JWT_TOKEN

### ─── LOGIN ADMIN (récupère le token) ──────────────────────────────────────

### LOGIN ADMIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

### ─── VEHICLE PUBLIC ─────────────────────────────────────────────────────────

### GET ALL AVAILABLE VEHICLES
GET {{baseUrl}}/vehicles

###

### GET VEHICLE BY ID
GET http://localhost:8080/vehicles/1

### ─── VEHICLE ADMIN ──────────────────────────────────────────────────────────

### GET ALL VEHICLES (admin)
GET http://localhost:8080/vehicles/admin/all
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzc5MjM0NiwiZXhwIjoxNzczNzk1OTQ2fQ.EclY3HwPLL4T_Y8P6U8ZYR0Bg51uXRKY1SAoDniSDhg
###

### CREATE VEHICLE
POST http://localhost:8080/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzkyODgzNSwiZXhwIjoxNzczOTMyNDM1fQ.qLI9aIs4RKEZjlXJgg5gmHwVNrSLHvC0OyUOajbG2uw
Content-Type: application/json

{
  "brand": "Toyota",
  "model": "Corolla",
  "year": 2022,
  "basePricePerDayTND": 150,
  "basePricePerDayUSD": 45,
  "basePricePerDayEUR": 42,
  "seats": 5,
  "transmission": "manual",
  "fuelType": "petrol",
  "category": "economy",
  "mileage": 15000,
  "description": "Voiture économique et fiable",
  "images": []
}

###

### UPDATE VEHICLE
PATCH {{baseUrl}}/vehicles/1
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzc5MjM0NiwiZXhwIjoxNzczNzk1OTQ2fQ.EclY3HwPLL4T_Y8P6U8ZYR0Bg51uXRKY1SAoDniSDhg

{
  "basePricePerDay": 60,
  "mileage": 0
}

###

### TOGGLE AVAILABLE
PATCH {{baseUrl}}/vehicles/1/toggle-available
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzc5MjM0NiwiZXhwIjoxNzczNzk1OTQ2fQ.EclY3HwPLL4T_Y8P6U8ZYR0Bg51uXRKY1SAoDniSDhg



###

### DELETE VEHICLE
DELETE {{baseUrl}}/vehicles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzc5MjM0NiwiZXhwIjoxNzczNzk1OTQ2fQ.EclY3HwPLL4T_Y8P6U8ZYR0Bg51uXRKY1SAoDniSDhg



### ─── VEHICLE PRICING ─────────────────────────────────────────────────────────

### GET ALL PRICINGS
GET {{baseUrl}}/vehicles/1/pricing
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzc5MjM0NiwiZXhwIjoxNzczNzk1OTQ2fQ.EclY3HwPLL4T_Y8P6U8ZYR0Bg51uXRKY1SAoDniSDhg



###

### CREATE PRICING RULE
POST {{baseUrl}}/vehicles/1/pricing
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzc5MjM0NiwiZXhwIjoxNzczNzk1OTQ2fQ.EclY3HwPLL4T_Y8P6U8ZYR0Bg51uXRKY1SAoDniSDhg

{
  "label": "Vacances été 2026",
  "startDate": "2026-07-01",
  "endDate": "2026-08-31",
  "pricePerDay": 80
}

###

### UPDATE PRICING RULE
PATCH {{baseUrl}}/vehicles/1/pricing/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzc5MjM0NiwiZXhwIjoxNzczNzk1OTQ2fQ.EclY3HwPLL4T_Y8P6U8ZYR0Bg51uXRKY1SAoDniSDhg

{
  "pricePerDay": 90
}

###

### DELETE PRICING RULE
DELETE {{baseUrl}}/vehicles/1/pricing/1
Authorization: Bearer {{adminToken}}

### CALCULATE PRICE
GET http://localhost:8080/vehicles/1/calculate-price?startDate=2026-08-31&endDate=2026-09-02

### ─── VARIABLES ─────────────────────────────────────────────────────────────
@baseUrl = http://localhost:8080
@adminToken = REPLACE_WITH_ADMIN_JWT_TOKEN

### ─── LOGIN ADMIN ───────────────────────────────────────────────────────────

### LOGIN ADMIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

### ─── PUBLIC ─────────────────────────────────────────────────────────────────

### CHECK AVAILABILITY
GET {{baseUrl}}/reservations/check-availability?vehicleId=1&startDate=2026-07-28&endDate=2026-08-02

###

### CREATE RESERVATION
POST {{baseUrl}}/reservations
Content-Type: application/json

{
  "vehicleId": 3,
  "startDate": "2026-04-28",
  "endDate": "2026-05-02",
  "guestFirstName": "John",
  "guestLastName": "Doe",
  "guestEmail": "john.doe@gmail.com",
  "guestPhone": "0612345678",
  "notes": "Je souhaite récupérer le véhicule à l'aéroport"
}

### ─── ADMIN ──────────────────────────────────────────────────────────────────

### GET ALL RESERVATIONS
GET {{baseUrl}}/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzkzMzg5OSwiZXhwIjoxNzczOTM3NDk5fQ.KOYgcJEi83GGXpBRZveqZ0Gg80_lONDIHg2uCK84rh4
###

### GET RESERVATION BY ID
GET {{baseUrl}}/reservations/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzkzMzg5OSwiZXhwIjoxNzczOTM3NDk5fQ.KOYgcJEi83GGXpBRZveqZ0Gg80_lONDIHg2uCK84rh4

###

### UPDATE RESERVATION
PATCH {{baseUrl}}/reservations/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzkzMzg5OSwiZXhwIjoxNzczOTM3NDk5fQ.KOYgcJEi83GGXpBRZveqZ0Gg80_lONDIHg2uCK84rh4

{
  "guestFirstName": "Jane",
  "guestPhone": "0698765432",
  "notes": "Récupération à la maison"
}

###

### UPDATE RESERVATION STATUS
PATCH {{baseUrl}}/reservations/1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzkzMzg5OSwiZXhwIjoxNzczOTM3NDk5fQ.KOYgcJEi83GGXpBRZveqZ0Gg80_lONDIHg2uCK84rh4

{
  "status": "confirmed"
}

###

### UPDATE RESERVATION STATUS - CANCELLED
PATCH {{baseUrl}}/reservations/1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzkzMzg5OSwiZXhwIjoxNzczOTM3NDk5fQ.KOYgcJEi83GGXpBRZveqZ0Gg80_lONDIHg2uCK84rh4

{
  "status": "cancelled"
}

###

### UPDATE RESERVATION STATUS - COMPLETED
PATCH {{baseUrl}}/reservations/1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzkzMzg5OSwiZXhwIjoxNzczOTM3NDk5fQ.KOYgcJEi83GGXpBRZveqZ0Gg80_lONDIHg2uCK84rh4

{
  "status": "completed"
}

###

### DELETE RESERVATION
DELETE {{baseUrl}}/reservations/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzkzMzg5OSwiZXhwIjoxNzczOTM3NDk5fQ.KOYgcJEi83GGXpBRZveqZ0Gg80_lONDIHg2uCK84rh4


### ─── VARIABLES ─────────────────────────────────────────────────────────────
@baseUrl = http://localhost:8080
@adminToken = REPLACE_WITH_ADMIN_JWT_TOKEN

### ─── LOGIN ADMIN ───────────────────────────────────────────────────────────

### LOGIN ADMIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

### ─── PUBLIC ─────────────────────────────────────────────────────────────────

### INITIATE PAYMENT
POST {{baseUrl}}/payments/initiate
Content-Type: application/json

{
  "reservationId": 6
}

###

### WEBHOOK (simuler Konnect)
GET {{baseUrl}}/payments/webhook?payment_ref=69bc9f1ecd2bd9f6ada9b8e2

### test uniquement en developpement pour lewebhook
GET http://localhost:8080/payments/webhook/test/69c6adc3cd2bd9f6adaea3da
### PAYMENT SUCCESS
GET {{baseUrl}}/payments/success?payment_ref=REPLACE_WITH_PAYMENT_REF

###

### PAYMENT FAIL
GET {{baseUrl}}/payments/fail?payment_ref=REPLACE_WITH_PAYMENT_REF

### ─── ADMIN ──────────────────────────────────────────────────────────────────

### GET ALL PAYMENTS
GET {{baseUrl}}/payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzk3MDQ2MywiZXhwIjoxNzczOTc0MDYzfQ.Qgw6S8_tfKh1c79vJUwbhH1QgqUJP7_CkjnjMkUB_LY

###

### GET PAYMENT BY ID
GET {{baseUrl}}/payments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzk3MDQ2MywiZXhwIjoxNzczOTc0MDYzfQ.Qgw6S8_tfKh1c79vJUwbhH1QgqUJP7_CkjnjMkUB_LY

###

### GET PAYMENTS BY RESERVATION
GET {{baseUrl}}/payments/reservation/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Mzk3MDQ2MywiZXhwIjoxNzczOTc0MDYzfQ.Qgw6S8_tfKh1c79vJUwbhH1QgqUJP7_CkjnjMkUB_LY

### CREATE BULK PRICING — tous les véhicules
POST http://localhost:8080/vehicles/pricing/bulk
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "label": "Vacances été 2026",
  "startDate": "2026-07-01",
  "endDate": "2026-08-31",
  "pricePerDayTND": 200,
  "pricePerDayUSD": 60,
  "pricePerDayEUR": 55
}

###

### CREATE BULK PRICING — véhicules spécifiques
POST http://localhost:8080/vehicles/pricing/bulk
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "label": "Promo SUV été 2026",
  "startDate": "2026-07-01",
  "endDate": "2026-08-31",
  "pricePerDayTND": 350,
  "pricePerDayUSD": 105,
  "pricePerDayEUR": 95,
  "vehicleIds": [1, 2, 3]
}

###

### UPDATE BULK PRICING — tous les véhicules
PATCH http://localhost:8080/vehicles/pricing/bulk
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "pricePerDayTND": 220,
  "pricePerDayUSD": 65,
  "pricePerDayEUR": 60
}

###

### UPDATE BULK PRICING — véhicules spécifiques
PATCH http://localhost:8080/vehicles/pricing/bulk
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "pricePerDayTND": 380,
  "vehicleIds": [1, 2]
}

###

### DELETE BULK PRICING — tous les véhicules
DELETE http://localhost:8080/vehicles/pricing/bulk
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{}

###

### DELETE BULK PRICING — véhicules spécifiques
DELETE http://localhost:8080/vehicles/pricing/bulk
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "vehicleIds": [1, 2, 3]
}